### ISSUE TITLE
Can't create a second user

### ISSUE THREAD

**Issue by Fahrradflucht** [jaumard/trails-example-express#1]
When I run the application as is and create a user, on every following `register` request I get:
```
{
  "error": "Not found"
}
```

In this context I also noticed, that after a disconnect the Passport object gets deleted and on any following auth request you get
```
{
  "error": "E_USER_NO_PASSWORD"
}
```

[PassportCheck.postman_collection.json.zip](https://github.com/jaumard/trails-example-express/files/288423/PassportCheck.postman_collection.json.zip)

--

I have the same issue in my app but I'm not sure if it's a config error or a bug on trailpack-passport so I thought I create it here first.

**Comment by jaumard** [comment]
You need to first logout, the register url also log the user. This example keep sessions so user is logged until you call logout.

**Comment by Fahrradflucht** [comment]
You are right. For some reason I thought disconnect means logout.
Sorry for bothering you.

**Comment by jaumard** [comment]
No problem, disconnect is useful for third party login like Twitter, FB... as it totally remove the passport entry in DB. Logout only clear/kill the sessions/token
